# Example markdownlint configuration with all properties set to their default value

# Default state for all rules
default: true

MD013:
  # Number of characters
  line_length: 100
  # Number of characters for headings
  heading_line_length: 100
  # Number of characters for code blocks
  code_block_line_length: 100
  # Include code blocks
  code_blocks: false
  # Include tables
  tables: false
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false
MD033:
  # Allowed elements
  allowed_elements: [code]